# -*- coding: utf-8 -*-
"""final-code-for-project da499_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GEg0Gk07xwR5aIZvycQS26EIob8P8IBg

# `***CV HANDLING***`:
"""

import pandas as pd
from zipfile import ZipFile

"""# `التعامل مع PDFور`"""

## تثبيت المكتبات والأدوات المطلوبة للمشروع.
# السطر الأول يثبت مكتبات Python التي سنستخدمها لتحميل الداتا، قراءة ملفات PDF،
# تحويلها إلى نص باستخدام OCR، ومعالجة البيانات باستخدام pandas.
# السطر الثاني يثبت برامج النظام (Tesseract و Poppler) اللازمة لاستخراج النص من الصور وملفات PDF.

!pip -q install kagglehub pymupdf pdf2image pytesseract pandas
!apt-get -qq install tesseract-ocr poppler-utils

#os → للتعامل مع الملفات والمجلدات في النظام
#re → لاستخدام الـ Regular Expressions لتنظيف النص
#fitz (PyMuPDF) → لقراءة النص من ملفات PDF
#pytesseract → لاستخراج النص من الصور باستخدام OCR
#pandas → لتنظيم البيانات في جداول (DataFrame)
#kagglehub → لتحميل الداتا من Kaggle
#convert_from_path → لتحويل صفحات PDF إلى صور عند الحاجة لاستخدام OCR

import os
import re
import fitz
import pytesseract
import pandas as pd
import kagglehub
from pdf2image import convert_from_path

# تحميل مجموعة البيانات الخاصة بالسير الذاتية من Kaggle باستخدام مكتبة kagglehub.
# يتم حفظ مسار البيانات في المتغير path، ثم نطبع المسار للتأكد من مكان حفظ الداتا.
# كما نتحقق من أن المسار موجود فعلاً في البيئة باستخدام os.path.exists.

path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
print("Dataset path:", path)
print("Exists:", os.path.exists(path))

#os.walk(path) → يتنقل داخل جميع مجلدات الداتا.endswith(".pdf") → للتأكد أن الملف هو سيرة ذاتية بصيغة PDF.
#append → لإضافة مسار الملف إلى القائمة.
#len(all_pdfs) → لمعرفة عدد السير الذاتية الموجودة في الداتا.
#all_pdfs[:5] → لعرض أول 5 ملفات للتأكد من أن القراءة تمت بشكل صحيح.

all_pdfs = []
for root, dirs, files in os.walk(path):
    for f in files:
        if f.lower().endswith(".pdf"):
            all_pdfs.append(os.path.join(root, f))
print("Total CV files:", len(all_pdfs))
print(all_pdfs[:5])

# الهدف من هذا الكود هو استخراج النص من ملفات السيرة الذاتية بصيغة PDF.
# نحاول أولاً استخراج النص مباشرة من ملف PDF باستخدام مكتبة fitz.
# إذا لم يتم استخراج النص بشكل جيد، نستخدم تقنية OCR لاستخراج النص من صور صفحات الـ PDF.

def extract_resume_text(pdf_path):

    text = ""

    try:
        doc = fitz.open(pdf_path)

        for page in doc:
            text += page.get_text() + "\n"

        doc.close()

    except Exception as e:
        print("Direct extraction failed:", pdf_path)

    if len(text.strip()) < 100:

        try:
            images = convert_from_path(pdf_path)

            ocr_text = ""

            for img in images:
                ocr_text += pytesseract.image_to_string(img) + "\n"

            text = ocr_text

        except Exception as e:
            print("OCR failed:", pdf_path)

    return text

#هون شلنا الشغلات الزايده بالنص تنظيف يعني
def clean_text(text):

    text = text.replace("ï¼​", " ")
    text = text.replace("\x0c", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()

# الهدف من هذا الكود هو معالجة جميع ملفات السيرة الذاتية واستخراج النص منها.
# يتم المرور على كل ملف PDF، ثم استخراج النص باستخدام الدالة السابقة،
# وبعد ذلك تنظيف النص وتخزين المعلومات الأساسية (اسم الملف، الفئة، النص)
# داخل قائمة records ليتم تحويلها لاحقاً إلى Dataset.
records = []

for i, pdf_path in enumerate(all_pdfs):

    try:

        raw_text = extract_resume_text(pdf_path)

        cleaned_text = clean_text(raw_text)

        records.append({
            "file_name": os.path.basename(pdf_path),
            "category": os.path.basename(os.path.dirname(pdf_path)),
            "text": cleaned_text
        })

        if (i+1) % 100 == 0:
            print("Processed", i+1)

    except Exception as e:
        print("Error:", pdf_path)



# الهدف من هذا الكود هو تحويل البيانات التي تم جمعها في القائمة records
# إلى جدول بيانات (DataFrame) باستخدام مكتبة pandas.
# بعد ذلك نعرض عدد الصفوف والأعمدة في الداتا، ثم نعرض أول عدة سجلات
# للتأكد من أن البيانات تم استخراجها وتنظيمها بشكل صحيح.
df = pd.DataFrame(records)
df = df.rename(columns={
    "category": "job_title",
    "text": "resume"
})
df.drop('file_name', axis=1, inplace=True)
print("Dataset shape:", df.shape)

df.head()

#هون بدنا نفلتر عشان ناخد ال it
it_categories = [
    "INFORMATION-TECHNOLOGY",
]

df_it = df[df["job_title"].isin(it_categories)]

df_it.head()

print("All resumes:", df.shape)
print("IT resumes:", df_it.shape)

df_it.to_csv("/content/it_resumes_dataset.csv", index=False)

#تنزيل عالجهاز
from google.colab import files

files.download("/content/it_resumes_dataset.csv")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df_it, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""# `التعامل مع الملفات الtext`

# ***`first file`***
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("muqaddasejaz/resume-cv-skills-extraction-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))

import pandas as pd
import os

# Explicitly set the path for this dataset to avoid conflicts


df2 = pd.read_csv(os.path.join(path, 'UpdatedResumeDataSet.csv'))
df2.rename(columns={'Category':'job_title', 'Resume':'resume'}, inplace=True)

print(df2.shape)
df2.head()

df2['job_title'].value_counts()



print("Dataset size:", df2.shape)

"""# ***`fillter the IT-job tiltle`***"""

it_jobs_list = [
    'Java Developer', 'Testing', 'DevOps Engineer', 'Python Developer',
    'Web Designing', 'Hadoop', 'Data Science', 'ETL Developer',
     'Database', 'DotNet Developer',
    'Automation Testing', 'Network Security Engineer', 'SAP Developer'
]

# 2. تصفية الـ DataFrame بحيث يحتوي فقط على هذه الوظائف
df2 = df2[df2['job_title'].isin(it_jobs_list)]

# 3. التأكد من النتيجة وحساب عدد كل وظيفة
print("IT Jobs Data Size:", df2.shape)
print("\nتوزيع الوظائف التقنية:")
print(df2['job_title'].value_counts())

# عرض عينة من البيانات المصفاة
display(df2.head())

"""ائلة التطوير والبرمجة (Development) Java Developer: يركز على بناء الأنظمة الخلفية (Backend) للمؤسسات الكبيرة والبنوك وتطبيقات الأندرويد.
Python Developer: متخصص مرن يعمل غالباً في مجالات الذكاء الاصطناعي، الأتمتة، أو تطوير المواقع السريعة.

DotNet Developer: يستخدم تقنيات مايكروسوفت لبناء تطبيقات موجهة لبيئة الويندوز والأنظمة السحابية للمؤسسات.

SAP Developer: متخصص في تخصيص وبرمجة أنظمة "سيب" (SAP) التي تدير الموارد المالية والبشرية للشركات العملاقة.

Web Designing: يهتم بالجانب البصري والتفاعلي للمواقع (Frontend)، وكيفية جعل تجربة المستخدم سهلة وجذابة.

عائلة البيانات والذكاء الاصطناعي (Data Science & Analytics) Data Science: يجمع بين الإحصاء والبرمجة لاستخراج أنماط وتوقعات من البيانات لمساعدة الشركات في اتخاذ القرار.
Hadoop: متخصص في إدارة ومعالجة "البيانات الضخمة" (Big Data) التي تفشل قواعد البيانات التقليدية في التعامل معها.

Database: المهندس المسؤول عن تصميم وبناء وحماية مستودعات البيانات والتأكد من سرعتها.

ETL Developer: يختص بعمليات "نقل وتجهيز البيانات"؛ حيث يسحبها من مصادر مختلفة، ينظفها، ثم يضعها في مكانها النهائي للتحليل.

عائلة الجودة والأمن والعمليات (Infrastructure & QA) Testing: الشخص المسؤول عن فحص البرامج يدوياً للتأكد من خلوها من العيوب قبل إطلاقها.
Automation Testing: مبرمج يكتب أكواداً خاصة تقوم بمهمة "الفحص" تلقائياً لضمان الجودة بسرعة أكبر.

DevOps Engineer: هو الرابط بين فريق البرمجة وفريق التشغيل، ويهتم بتسريع وصول التحديثات إلى المستخدمين بشكل آلي.

Network Security Engineer: حارس الأمن الرقمي الذي يحمي الشبكات والبيانات من الاختراقات والهجمات السيبرانية.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df2, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""# ***`secound`***"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("haidermaseeh/resume-dataset")

print("Path to dataset files:", path)

print(os.listdir(path))

import pandas as pd
import os

df3= pd.read_csv(os.path.join(path, 'Resume dataset.csv'))

print(df3.shape)
df3.head()

df3['category'].value_counts()

"""# ***عملنا فلتر وتغير اسامي***"""

# تغير اسامي ال الوظائف
it_mapping = {
    'Java Developers/Architects Resumes': 'java_dev',
    'Web Developer Resumes': 'web_dev',
    'SQL Developers Resumes': 'sql_dev',
    'Network and Systems Administrators Resumes': 'sys_admin',
    'Datawarehousing, ETL, Informatica Resumes': 'etl_data_eng',
    'Business Intelligence, Business Object Resumes': 'bi_dev'
}

# 2. تصفية الداتا سيت (إبقاء الـ IT فقط)
df3 = df3[df3['category'].isin(it_mapping.keys())].copy()

# 3. تغيير الأسماء للأسماء المختصرة
df3['category'] = df3['category'].map(it_mapping)
df3.drop('job_title', axis=1, inplace=True)
df3.rename(columns={'category': 'job_title','Text':'resume'}, inplace=True)

# التأكد من النتائج
print("Current IT Categories:")
print(df3['job_title'].value_counts())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***data exploring***"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df3, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""**third dataset**

---

هاي داتا اصلا كانت جدول
"""



import kagglehub
import pandas as pd
import os

# تحميل الداتا
path = kagglehub.dataset_download("souptikghosh/resume-dataset")

# عرض الملفات
print(os.listdir(path))

# قراءة CSV
df4_temp = pd.read_csv(path + "/resume_dataset_2.csv", encoding='latin-1')

# عرض البيانات
print('...........................')

# تغيير اسم العمود
df4_temp.rename(columns={
    'Years_Experience': 'experience_years',
    'Job_Role': 'job_title',
    'Resume_Text': 'resume'
}, inplace=True)

df4_temp['clean_resume'] = ''
df4_temp['experience_years'] = df4_temp['experience_years'].fillna(0).astype(float)
df4_temp['job_title'] = df4_temp['job_title'].fillna('').astype(str)
df4_temp['resume'] = df4_temp['resume'].fillna('').astype(str)
# Assign processed data to df4
df4 = df4_temp[['job_title', 'resume', 'experience_years']]

df4.columns
df4.head()

df4["job_title"].value_counts()

it_mapping={"Data Scientist":"Data Science","Software Engineer":"Software Engineer"}
df4 = df4[df4["job_title"].isin(it_mapping.keys())]
df4.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df4, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""**four_dataset**

---


"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("nikitagupta1812/resume-dataset")

print("Path to dataset files:", path)

import pandas as pd
import os


df5 = pd.read_csv(os.path.join(path,'Resume_Screening_Dataset_50000.csv'))

print(df5.shape)
df5.head()

df5["Specialization"].value_counts()

import pandas as pd

# 1️⃣ فلترة تخصصات IT
it_keywords = "IT|Computer Science|Data Science|AI"

df_it = df5[df5["Specialization"].str.contains(it_keywords, case=False, na=False)]

# 2️⃣ إنشاء DataFrame جديد فيه 3 أعمدة فقط
df_new = pd.DataFrame()

df_new["job_title"] = df_it["Specialization"]

df_new["resume"] = (
    "Skills: " + df_it["Skills"].astype(str) +
    " | Projects: " + df_it["Projects_Count"].astype(str) +
    " | Certifications: " + df_it["Certifications"].astype(str) +
    " | Degree: " + df_it["Degree"].astype(str)
)

df_new["experience_years"] = df_it["Experience_Years"]

# 3️⃣ عرض النتيجة
df_new.head()

df_new.shape



import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df_new, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""**6_dataset**

---


"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("amaankhan24/resume-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))

import os
df6= pd.read_csv(os.path.join(path,'Combined_Tech_and_NonTech_Category_Resume.csv'))
df6.head()

df6["Category"].value_counts().to_string()

# 1️⃣ فلترة وظائف IT
it_jobs = [
    "Software Engineer",
    "Web Developer",
    "Data Analyst",
    "Machine Learning Engineer",
    "AI Researcher",
    "Cybersecurity Analyst",
    "Systems Analyst",
    "Database Administrator",
    "Cloud Architect",
    "Network Security Engineer",
    "Python Developer",
    "Java Developer",
    "ETL Developer",
    "DotNet Developer"
]

df6= df6[df6["Category"].isin(it_jobs)]

df6 = df6.rename(columns={"Category": "job_title"})
df6 = df6.iloc[:, 1:]
# 3️⃣ عرض النتيجة
df6.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df6, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""7dataset"""

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("kilyfaa/sintesis-resume-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))

import pandas as pd
import os


df7 = pd.read_csv(os.path.join(path,'preprocessed_dataset.csv'))
df7['category'].value_counts()
df7.head()

it_categories = [
    "java developer",
    "sql developer",
    "dotnet developer",
    "web designing",
    "sap developer",
    "data science",
    "etl developer",
    "devops",
    "information technology",
    "database",
    "python developer",
    "react developer",

    "network security engineer",
    "testing"
]
df7= df7[df7["category"].isin(it_categories)]
df7 = df7.rename(columns={
    "category": "job_title",
    "test": "resume"
})
df7.shape

df7.head()



import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df7, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""**dataset_8**"""

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("wahib04/multilabel-resume-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))



import pandas as pd
import os


df8 = pd.read_csv(os.path.join(path,'data.csv'))

df8.head()

df8['Label'].value_counts().to_string()

# define IT keywords
it_keywords = [

    "database_administrator",
    "software_developer",
    "web_developer",
    "python_developer",
    "security_analyst",
    "network_administrator"
]

# Rename 'Label' column to 'job_title'
df8.rename(columns={'Label': 'job_title','Resume':'resume'}, inplace=True)

# normalize text
df8['job_title'] = df8['job_title'].str.lower()

# split multi-label rows
df8['job_title'] = df8['job_title'].str.split(',')

df8 = df8.explode('job_title')

# clean spaces
df8['job_title'] = df8['job_title'].str.strip()

# filter only IT jobs
it_df8 = df8[df8['job_title'].isin(it_keywords)]

# check distribution
it_df8['job_title'].value_counts()





import matplotlib.pyplot as plt
import seaborn as sns

# Reset the index to ensure uniqueness after the explode operation
df8 = df8.reset_index(drop=True)

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=it_df8, x='job_title', hue='job_title', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

"""***`combain all data `***

---


"""

import pandas as pd

# 1. تجهيز البيانات من المصدر الأول (PDFs)
# نختار فقط التخصصات التقنية من البيانات المستخرجة من الملفات
it_categories_pdf_data = ["INFORMATION-TECHNOLOGY"]
df_it_pdf = df[df["job_title"].isin(it_categories_pdf_data)].copy()

# 2. توحيد أسماء الأعمدة في الجداول المختلفة لضمان الدمج الصحيح
if 'Resume' in df6.columns:
    df6.rename(columns={'Resume': 'resume'}, inplace=True)

if 'text_cv' in df7.columns:
    df7.rename(columns={'text_cv': 'resume'}, inplace=True)
if 'Resume' in it_df8.columns:
    df6.rename(columns={'Resume': 'resume'}, inplace=True)

# 3. قائمة الجداول السبعة المراد دمجها
# df_it_pdf (المصدر 1), df2, df3, df4, df_new (المصدر 5), df6, df7
dfs_to_concat = [df_it_pdf, df2, df3, df4, df_new, df6, df7,it_df8]

# 4. عملية الدمج (Concatenation)
# ignore_index=True لإعادة ترتيب الأسطر من الصفر
df_all = pd.concat(dfs_to_concat, ignore_index=True)

# 5. تنظيف عمود سنوات الخبرة
# تحويل العمود لرقمي، ومعالجة القيم المفقودة (NaN) بوضع صفر مؤقتاً
df_all['experience_years'] = pd.to_numeric(df_all['experience_years'], errors='coerce').fillna(0)

print(df_all.shape)

df_all.head()

"""befor cleaning i will extract the year_expersce

---

وكككككك هون عملت كود بطلع السنوات الخبره من النص بجيمع اشكال يلي ممكن تيجيها مثلاااOver twenty years of experience in IT", "Over 10+ years of professional experience", "Worked from 1990-2050", "3+ years in data science", "9 months of internship رح تتعامل مع كل هدول واطلعهم تتخيلواااااااا يس انا ذكيعه ما شاءلله علي " word2number هاي المكتبه مشان تحل مشكله الارقام لو كانت مكتوبه مثلا one------>1 بتحوله لرقم بس
"""

import re
from datetime import datetime

import re
from datetime import datetime

def extract_clean_experience_years(text):
    if not text or str(text).lower() == 'nan':
        return 0.0

    # 1. تحويل النص لصغير وقصه عند أول ظهور لقسم غير مهني (لإزالة الـ 2.8)
    text_lower = str(text).lower()
    split_keywords = ['activities', 'education', 'awards', 'honor society', 'additional information']

    clean_text = text_lower
    for kw in split_keywords:
        if kw in clean_text:
            clean_text = clean_text.split(kw)[0]
            break

    # 2. البحث عن التواريخ في الجزء المهني فقط
    date_pattern = re.compile(r'(\d{1,2}/)?(\d{4})\s*(?:to|-|–)\s*(\d{1,2}/)?(\d{4}|current|present|now)')
    found_spans = date_pattern.findall(clean_text)

    worked_months = set()
    current_date = datetime.now()

    for start_m, start_y, end_m, end_y in found_spans:
        try:
            s_year = int(start_y)
            s_month = int(start_m.replace('/', '')) if start_m else 1

            if end_y.lower() in ('current', 'present', 'now'):
                e_year = current_date.year
                e_month = current_date.month
            else:
                e_year = int(end_y)
                e_month = int(end_m.replace('/', '')) if end_m else 12

            # إضافة الشهور للـ Set لمنع التكرار
            for m in range(s_year * 12 + s_month, e_year * 12 + e_month + 1):
                worked_months.add(m)
        except:
            continue

    # إرجاع الرقم فقط
    return round(len(worked_months) / 12, 1)



def apply_smart_extraction(row):
    if row['experience_years'] > 0:
        return row['experience_years']
    return extract_clean_experience_years(str(row['resume']))
df_all["experience_years"] = df_all.apply(apply_smart_extraction, axis=1)
df_all.head()

"""# Cleaning Data:

1.  URLs
2. hashtags
1.   mention
2. special letters
1. punctuations




---




"""

import re

import re

def clean_text(txt):
    txt = str(txt)

    # URLs
    txt = re.sub(r'http\S+|www\S+', ' ', txt)

    #emails
    txt = re.sub(r'\S+@\S+', ' ', txt)

    #mentions (social media)
    txt = re.sub(r'@\w+', ' ', txt)

    #hashtags (remove # but keep word)
    txt = re.sub(r'#(\w+)', r'\1', txt)

    #RT / CC noise
    txt = re.sub(r'\bRT\b|\bcc\b', ' ', txt)

    #remove meaningless punctuation and
    #KEEP: + # . _ / - (important for skills like C++, .NET, node.js)
    txt = re.sub(r'[!"$%&\'()*,:;<=>?@\[\]^`{|}~]', ' ', txt)

    #fix weird encoding (optional but very useful)
    txt = txt.encode('utf-8', errors='ignore').decode('utf-8')

    #remove non-ascii junk
    txt = re.sub(r'[^\x00-\x7f]', ' ', txt)

    #remove standalone numbers ONLY
    txt = re.sub(r'(?<!\w)\d+(?!\w)', ' ', txt)

    #normalize spaces
    txt = re.sub(r'\s+', ' ', txt)

    return txt.lower().strip()

# Re-apply to your dataframe
df_all['cleanresume'] = df_all['resume'].astype(str).apply(clean_text)

"""✅ keep='first' يعني الاحتفاظ بالصف الأول لكل نص مكرر، وحذف الباقي.
✅ reset_index(drop=True) يعيد ترقيم الصفوف بعد الحذف.
"""

# إزالة الصفوف التي تحتوي على نفس النص في cleanresume
# لنفترض عندك عمود resume و job_title و experience_years
print("Number of rowsلbefor smart deduplication:", df_all.shape[0])
df_all = df_all.drop_duplicates(subset=['cleanresume', 'job_title','experience_years'], keep='first').reset_index(drop=True)

print("Number of rows after smart deduplication:", df_all.shape[0])

# تحقق
print(df_all.shape)
print(df_all.sample(3))

"""***`normlize name `***"""

df_all['job_title'].value_counts()



# 1. CLEAN TEXT
df_all['job_title'] = (
    df_all['job_title']
    .str.lower()
    .str.strip()
    .str.replace(' ', '_', regex=False)
    .str.replace('-', '_', regex=False)
)

# Unify key duplicates
df_all['job_title'] = df_all['job_title'].replace({
    "java_developer":           "java_dev",
    "python_developer":         "python_dev",
    "web_developer":            "web_dev",
    "sql_developer":            "sql_dev",
    "etl_developer":            "etl_data_eng",
    "machine_learning_engineer":"ml_engineer",
    "data_scientist":           "data_science",
})

# 2. MAP TO GROUPS
mapping = {
    # 💻 Software Engineering
    "software_developer":   "software_engineering",
    "software_engineer":    "software_engineering",
    "java_dev":             "software_engineering",
    "dotnet_developer":     "software_engineering",
    "react_developer":      "software_engineering",
    "python_dev":           "software_engineering",


    # 📊 Data & AI
    "data_science":         "data_ai",
    "data_analyst":         "data_ai",
    "ai":                   "data_ai",
    "ai_researcher":        "data_ai",
    "ml_engineer":          "data_ai",   # ✅ use renamed key
    "etl_data_eng":         "data_ai",
    "sql_dev":              "data_ai",
    "bi_dev":               "data_ai",
    "hadoop":               "data_ai",
    "database":             "data_ai",

    # 🏢 IT Systems
    "it":                   "it_systems",
    "information_technology":"it_systems",
    "computer_science":     "it_systems",
    "systems_analyst":      "it_systems",
    "sys_admin":            "it_systems",
    "project_manager":      "it_systems",

    # 🔐 Infrastructure & Security
     # ✅ use renamed key
    "web_designing":        "infrastructure",
    "network_administrator":"infrastructure",
    "network_security_engineer": "infrastructure",
    "security_analyst":     "infrastructure",
    "cybersecurity_analyst":"infrastructure",

    "database_administrator":"infrastructure",
    "cloud_architect":      "infrastructure",
    "devops":               "infrastructure",
    "devops_engineer":      "infrastructure",
    "testing":              "infrastructure",
    "automation_testing":   "infrastructure",
    "sap_developer":        "infrastructure",
    "web_dev":              "infrastructure",
}

df_all['job_group'] = df_all['job_title'].replace(mapping)

# 3. CHECK UNMAPPED (fixed)
expected_groups = {"software_engineering", "data_ai", "it_systems", "infrastructure"}
unmapped = df_all[~df_all['job_group'].isin(expected_groups)]
print("Unmapped values:")
print(unmapped['job_title'].value_counts())

# 4. FINAL CHECK
print(df_all['job_group'].value_counts())

expected_groups = {"software_engineering", "data_ai", "it_systems", "infrastructure"}
unmapped = df_all[~df_all['job_group'].isin(expected_groups)]
print("Unmapped values:")
print(unmapped['job_title'].value_counts())

"""Series([], dtype: int64)

✔️ هذا يعني:

كل البيانات انصنفت بشكل صحيح 100%
ما في أي job_title ضايع
إحنا ما كنا نعمل “تصنيفات أسماء”
إحنا كنا نعمل:

Grouping حسب طبيعة الشغل الحقيقي في سوق العمل

يعني:
مش “شو اسم الوظيفة”
بل “شو نوع الشغل فعليًا”

🧠 كيف فكرنا بالتقسيم؟

قسمنا البيانات حسب 4 عائلات وظيفية كبيرة 👇

💻 1. software_engineering
شو دخل فيها؟

أي شخص “يبني برامج أو تطبيقات”

أمثلة:
software_developer
java_dev / python_dev
dotnet / react
web_developer
🎯 ليش جمّعناهم؟

لأنهم كلهم:

يكتبوا كود ويب/برمجيات/أنظمة

✔ نفس المهارة الأساسية = Programming

📊 2. data_ai
شو دخل فيها؟

أي شخص “يحلل بيانات أو يبني نماذج ذكاء اصطناعي”

أمثلة:
data_science
data_analyst
machine_learning_engineer
ai_researcher
sql / etl / bi
🎯 ليش؟

لأنهم كلهم:

يشتغلوا على البيانات (مش بناء تطبيقات)

✔ نفس المجال = Data Pipeline + ML + Analytics

🏢 3. it_systems
شو دخل فيها؟

أشخاص يديروا الأنظمة والبنية الإدارية

أمثلة:
systems_administrator
sys_admin
project_manager
information_technology
computer_science
🎯 ليش؟

لأنهم:

مش بيبنوا منتجات، بل يديروا بيئة العمل

✔ نفس الدور = إدارة وتشغيل نظم

🔐 4. infrastructure
شو دخل فيها؟

كل شيء متعلق بـ:

الشبكات
السيرفرات
الأمن
DevOps
أمثلة:
network_admin
cybersecurity
cloud_architect
devops
database_admin
testing
🎯 ليش؟

لأنهم:

مسؤولين عن “البيئة اللي يشتغل عليها النظام”

✔ نفس المجال = تشغيل + حماية + بنية تحتية

⚖️ ليش هذا التقسيم منطقي؟

لأنه في الحقيقة في الشركات:

القسم	الوظيفة
Software	بناء المنتج
Data/AI	تحليل واتخاذ قرار
IT Systems	إدارة النظام
Infrastructure	تشغيل وحماية النظام
📌 أهم نقطة فهميها

إحنا ما قسمنا حسب:
❌ أسماء الوظائف
✔ قسمنا حسب نوع المهارة الأساسية
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df_all, x='job_group', hue='job_group', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

# عد القيم الفارغة في عامود سنوات الخبرة
null_count = df_all['experience_years'].isnull().sum()

print(f"عدد القيم الفارغة (Null) في سنوات الخبرة: {null_count}")

df_all.head()

"""**remove stopword form clean CV**

---


"""

df_all.shape

import os

output_path = '/content/_final24/4_cleaned_resumes.csv'

# Ensure the directory exists
os.makedirs(os.path.dirname(output_path), exist_ok=True)

# احفظ DataFrame
df_all.to_csv(output_path, index=False)
print(f"Saved to {output_path}")

from google.colab import files

files.download(output_path)

"""# **job_handling**"""

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("adityarajsrv/job-descriptions-2025-tech-and-non-tech-roles")

print("Path to dataset files:", path)
print(os.listdir(path))

import pandas as pd
import os
import pandas as pd
import os


job=pd.read_csv(os.path.join(path,'job_dataset.csv'))
job.head()

job["Title"].unique()

job.shape

job['Title'].value_counts()

import pandas as pd
import re

# 1. إنشاء الجدول المستقل


# 2. المسمى الوظيفي
job['job_title'] = job['Title'].str.strip()

# 3. معالجة "فترة" سنوات الخبرة (Year of Experience)
import re
import numpy as np

def clean_experience(exp):
    if exp is None or str(exp).strip() == "nan":
        return 0

    exp = str(exp).strip()

    # ┅ Case 1: range (0-1)
    if "-" in exp:
        try:
            start, end = exp.split("-")
            return (float(start) + float(end)) / 2
        except:
            return 0

    # ┅ Case 2: "3+"
    if "+" in exp:
        try:
            return float(exp.replace("+", "").strip())
        except:
            return 0

    # ┅ Case 3: normal number
    try:
        return float(exp)
    except:
        return 0

# Apply the cleaning function to create 'year_exper'
job['year_exper'] = job['YearsOfExperience'].apply(clean_experience)

# 4. دمج النصوص في عمود واحد (job_text)
job['job_text'] = (
    "skills: " + job['Skills'].fillna('') +
    " responsibilities: " + job['Responsibilities'].fillna('') +
    " keywords: " + job['Keywords'].fillna('')
)

# Drop original source columns
job.drop(columns=['Title', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords','ExperienceLevel',"JobID"], inplace=True)

# عرض النتيجة

job.head()

"""clean the text of job(tha same of resume)"""

import re

import re

def clean_text(txt):
    txt = str(txt)

    # 🔥 URLs
    txt = re.sub(r'http\S+|www\S+', ' ', txt)

    # 🔥 emails
    txt = re.sub(r'\S+@\S+', ' ', txt)

    # 🔥 mentions (social media)
    txt = re.sub(r'@\w+', ' ', txt)

    # 🔥 hashtags (remove # but keep word)
    txt = re.sub(r'#(\w+)', r'\1', txt)

    # 🔥 RT / CC noise
    txt = re.sub(r'\bRT\b|\bcc\b', ' ', txt)

    # ❌ remove only meaningless punctuation
    # ✔ KEEP: + # . _ / - (important for skills like C++, .NET, node.js)
    txt = re.sub(r'[!"$%&\'()*,:;<=>?@\[\]^`{|}~]', ' ', txt)

    # 🔥 fix weird encoding (optional but very useful)
    txt = txt.encode('utf-8', errors='ignore').decode('utf-8')

    # 🔥 remove non-ascii junk
    txt = re.sub(r'[^\x00-\x7f]', ' ', txt)

    # 🔥 remove standalone numbers ONLY
    txt = re.sub(r'(?<!\w)\d+(?!\w)', ' ', txt)

    # 🔥 normalize spaces
    txt = re.sub(r'\s+', ' ', txt)

    return txt.lower().strip()

import re

import re

def clean_job_title(title):
    title = str(title).lower()

    # 🔥 خطوة مهمة جداً: توحيد كل المسافات
    title = re.sub(r'\s+', ' ', title)

    # 🔥 توحيد الرموز قبل أي شيء
    title = title.replace('-', ' ')
    title = title.replace('/', ' ')
    title = title.replace('.', ' ')

    title = re.sub(r'\s+', ' ', title)  # مرة ثانية بعد الرموز

    # 🔥 إزالة مستويات الخبرة (بدون \b)
    title = re.sub(r'entry\s*level|mid\s*level|experienced|internship|intern|trainee|fresher', '', title)

    title = re.sub(r'junior|jr|senior|sr|lead|principal', '', title)

    # 🔥 حذف الأرقام
    title = re.sub(r'\d+', '', title)

    # تنظيف نهائي
    title = re.sub(r'\s+', ' ', title).strip()

    return title
job['job_title_clean'] = job['job_title'].apply(clean_job_title)

job_profiles = job.groupby("job_title_clean").agg({
    "job_text": " ".join,
    "year_exper": "max"
}).reset_index()
job_profiles['clean_text'] = job_profiles['job_text'].apply(clean_text)
job_profiles.head()

job_profiles["job_title_clean"].unique()

it_keywords = [
    'developer', 'engineer', 'data', 'ai',
    'machine learning', 'cloud', 'devops',
    'backend', 'frontend', 'python',
    'java', 'net', 'javascript',
     'robotics', 'vr','cybersecurity','cyber','hacker','security','network',
]

df_job = job_profiles[
    job_profiles['job_title_clean'].str.contains('|'.join(it_keywords), case=False, na=False)
].copy()

df_job['job_title_clean'].unique()

mapping = {

# =========================
# 💻 SOFTWARE ENGINEERING
# =========================
"android app developer": "software_engineering",
"android developer": "software_engineering",
"android engineer": "software_engineering",
"android solutions engineer": "software_engineering",
"android solutions architect": "software_engineering",
"associate android developer": "software_engineering",

"ios app developer": "software_engineering",
"ios application developer": "software_engineering",
"ios developer": "software_engineering",
"ios engineer": "software_engineering",
"ios mobile developer": "software_engineering",
"ios mobile app engineer": "software_engineering",
"ios solutions engineer": "software_engineering",

"backend developer": "software_engineering",
"frontend developer": "software_engineering",
"full stack developer": "software_engineering",
"software developer": "software_engineering",
"software engineer": "software_engineering",
"web developer": "software_engineering",

"java developer": "software_engineering",
"javascript developer": "software_engineering",
"python developer": "software_engineering",
"net developer": "software_engineering",
"swift developer": "software_engineering",

"game developer": "software_engineering",
"fintech engineer": "software_engineering",
"blockchain developer": "software_engineering",
"ar vr developer": "software_engineering",
"iot engineer": "software_engineering",
"robotics engineer": "software_engineering",
"vibe coder": "software_engineering",
"associate ios engineer": "software_engineering",
"graduate ios developer": "software_engineering",

# =========================
# 📊 DATA & AI
# =========================
"ai engineer": "data_ai",
"ai prompt engineer": "data_ai",

"data analyst": "data_ai",
"data analyst data scientist": "data_ai",
"data engineer": "data_ai",
"data science": "data_ai",
"data science associate": "data_ai",
"data science team": "data_ai",
"data scientist": "data_ai",
"big data specialist": "data_ai",
"bi analyst": "data_ai",
"market research analyst": "data_ai",

"machine learning engineer": "data_ai",
"machine learning scientist": "data_ai",
"ml ai engineer": "data_ai",
"ml engineer": "data_ai",
"ml infrastructure engineer": "data_ai",
"associate cybersecurity analyst": "data_ai",

# =========================
# 🏢 IT SYSTEMS
# =========================
"associate system engineer": "it_systems",
"system engineer": "it_systems",
"system engineer automation specialist": "it_systems",
"system engineer cloud & automation": "it_systems",
"system engineer cloud focus": "it_systems",
"system engineer devops integration": "it_systems",
"system engineer monitoring": "it_systems",
"system engineer security": "it_systems",
"system engineer virtualization": "it_systems",

"it support networking focus": "it_systems",
"operations manager": "it_systems",
"project manager": "it_systems",
"business analyst": "it_systems",
"computer science": "it_systems",
"entry level network analyst": "it_systems",


# =========================
# 🔐 INFRASTRUCTURE & SECURITY
# =========================
"cloud": "infrastructure",
"cloud architect": "infrastructure",
"associate cloud architect": "infrastructure",
"enterprise cloud architect": "infrastructure",
"hybrid cloud architect": "infrastructure",
"multi cloud architect": "infrastructure",
"cloud engineer": "infrastructure",
"cloud automation engineer": "infrastructure",
"cloud cost optimization architect": "infrastructure",
"cloud devsecops architect": "infrastructure",
"cloud infrastructure architect": "infrastructure",
"cloud infrastructure security architect": "infrastructure",
"cloud migration specialist": "infrastructure",
"cloud network engineer": "infrastructure",
"cloud platform architect": "infrastructure",
"cloud security analyst": "infrastructure",
"cloud security architect": "infrastructure",
"cloud solutions architect": "infrastructure",
"cloud solutions associate": "infrastructure",

"devops engineer": "infrastructure",
"devops cloud architect": "infrastructure",

"network": "infrastructure",
"network analyst": "infrastructure",
"network engineer": "infrastructure",
"network automation engineer": "infrastructure",
"network operations center (noc) engineer": "infrastructure",
"network security engineer": "infrastructure",
"network support engineer": "infrastructure",
"enterprise network engineer": "infrastructure",
"infrastructure network engineer": "infrastructure",
"telecom & network engineer": "infrastructure",

"cybersecurity": "infrastructure",
"cybersecurity analyst": "infrastructure",
"cybersecurity risk analyst": "infrastructure",
"cybersecurity support analyst": "infrastructure",
"cyber defense analyst": "infrastructure",
"information security analyst": "infrastructure",
"information security specialist": "infrastructure",
"security analyst": "infrastructure",
"soc analyst": "infrastructure",
"ethical hacker": "infrastructure",
"security & network engineer": "infrastructure",

"qa engineer": "infrastructure",
"test automation engineer": "infrastructure",
"software tester (sdet)": "infrastructure",

"site reliability engineer": "infrastructure",
"associate network engineer": "infrastructure",
"graduate network engineer": "infrastructure",
"graduate security analyst": "infrastructure",
}
df_job['job_group'] = df_job['job_title_clean'].replace(mapping)
df_job['job_group'].value_counts()

unmapped = df_job[df_job['job_group'].isna()]
print(unmapped['job_title_clean'].value_counts())

df_job.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

ax = sns.countplot(data=df_job, x='job_group', hue='job_group', palette='Spectral', legend=False)

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')

plt.title('Distribution of IT Job Profiles in Dataset', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Job Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Resumes', fontsize=14, fontweight='bold')

plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()

plt.show()

df_job.shape

output_path = '/content/_final24/4_cleaned_job.csv'

# احفظ DataFrame
df_job.to_csv(output_path, index=False)
print(f"Saved to {output_path}")

from google.colab import files

files.download(output_path)

"""# ***`tf-idf baseline model`***"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv_df = pd.read_csv('it_resumes_dataset.csv')
job_df = pd.read_csv('_finalnewwwww_cleaned_job.csv')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# تجهيز cv_df مع job_group
cv_df = job_df[['job_title', 'resume', 'job_group']].copy()

# حل مشكلة القيم الفاضية
cv_df['resume'] = cv_df['resume'].fillna('').astype(str)

# TF-IDF
tfidf_vec = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vec.fit_transform(cv_df['resume'])

# اختيار الوظيفة المطلوبة
target_index = 0
selected_job_description = job_df['cleanresume'].iloc[target_index]
selected_job_title = job_df['job_title'].iloc[target_index]
target_job_group = job_df['job_group'].iloc[target_index]

# تحويل وصف الوظيفة إلى TF-IDF
job_vector = tfidf_vec.transform([selected_job_description])

# حساب similarity
similarity_scores = cosine_similarity(job_vector, tfidf_matrix).flatten()

# إضافة Match Score
cv_df['Match_Score'] = similarity_scores

# ترتيب النتائج
k = 10
ranked_results = cv_df.sort_values(by='Match_Score', ascending=False).reset_index(drop=True)

# تحديد هل المرشح relevant أم لا
ranked_results['is_relevant'] = ranked_results['job_group'] == target_job_group

# Top K
top_k_results = ranked_results.head(k)

# Precision@K
precision_at_k = top_k_results['is_relevant'].sum() / k

# Recall@K
total_relevant = ranked_results['is_relevant'].sum()

if total_relevant > 0:
    recall_at_k = top_k_results['is_relevant'].sum() / total_relevant
else:
    recall_at_k = 0

# MRR
mrr = 0
for i, relevant in enumerate(ranked_results['is_relevant'], start=1):
    if relevant:
        mrr = 1 / i
        break

print("Selected Job Title:", selected_job_title)
print(f"Precision@{k}: {precision_at_k:.4f}")
print(f"Recall@{k}: {recall_at_k:.4f}")
print(f"MRR: {mrr:.4f}")

top_k_results[['job_title', 'resume', 'job_group', 'Match_Score', 'is_relevant']]

"""# ***`SentenceTransformer('all-mpnet-base-v2')`***"""

import numpy as np
from sentence_transformers import SentenceTransformer, util

# ============================================================
# MODEL + EMBEDDINGS (MPNET)
# ============================================================

model = SentenceTransformer('all-mpnet-base-v2')

resume_emb = model.encode(
    df_all['cleanresume'].tolist(),
    show_progress_bar=True,
    convert_to_tensor=True
)

job_emb = model.encode(
    df_job['clean_text'].tolist(),
    batch_size=16,
    convert_to_tensor=True
)

sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp):
    return min(exp / 5, 1)

# ============================================================
# FUNCTION (NO job_group)
# ============================================================

def get_top_cvs_no_group(job_idx, top_k=10):

    results = []

    job_sims = sim_matrix[:, job_idx]
    dynamic_threshold = np.mean(job_sims) + 0.05

    for i in range(len(df_all)):

        sim = sim_matrix[i, job_idx]

        if sim < dynamic_threshold:
            continue

        exp = df_all.loc[i, 'experience_years']
        exp_score = normalize_experience(exp)

        final_score = (0.8 * sim) + (0.2 * exp_score)

        explanation = [
            "No group filtering applied",
            "Semantic matching only"
        ]

        results.append({
            "resume_id": i,
            "cv_text": df_all.loc[i, 'cleanresume'],
            "score": float(final_score),
            "similarity": float(sim),
            "explanation": explanation
        })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):

    print(f"\n================ JOB {j} ================")
    print("Job Group:", df_job.iloc[j]['job_group'])

    results = get_top_cvs_no_group(j)

    for rank, r in enumerate(results):

        print("\n----------------------------")

        print("Rank:", rank + 1)
        print("CV:\n", df_all.iloc[r["resume_id"]]["cleanresume"][:300])
        print("Score:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))

        print("Explanation:")
        for e in r["explanation"]:
            print(" -", e)



threshold = 0.65

ground_truth = {
    j: np.where(sim_matrix[:, j] >= threshold)[0].tolist()
    for j in range(len(df_job))
}
def precision_at_k(pred, true, k):
    pred = pred[:k]
    return len(set(pred) & set(true)) / max(len(pred), 1)

def recall_at_k(pred, true, k):
    return len(set(pred) & set(true)) / max(len(true), 1)

def mrr(pred, true):
    for i, p in enumerate(pred):
        if p in true:
            return 1 / (i + 1)
    return 0
def evaluate_system(pred_fn, K_val=5):

    precisions, recalls, mrrs = [], [], []

    for j in range(len(df_job)):

        results = pred_fn(j)
        pred = [r["resume_id"] for r in results]
        true = ground_truth[j]

        # 🔥 مهم: إذا ما في ground truth لا نحسب
        if len(true) == 0:
            continue

        precisions.append(precision_at_k(pred, true, K_val))
        recalls.append(recall_at_k(pred, true, K_val))
        mrrs.append(mrr(pred, true))

    return {
        "Precision@K": np.mean(precisions) if precisions else 0,
        "Recall@K": np.mean(recalls) if recalls else 0,
        "MRR": np.mean(mrrs) if mrrs else 0
    }
k = 5

results_no = evaluate_system(get_top_cvs_no_group, k)

import pandas as pd

df_results = pd.DataFrame(

    [["No Group", results_no["Precision@K"], results_no["Recall@K"], results_no["MRR"]]],

columns=["Model", "Precision@5", "Recall@5", "MRR"])

print(df_results)

import matplotlib.pyplot as plt
import numpy as np
import random

metrics = ["Precision@5", "Recall@5", "MRR"]
values = [results_no["Precision@K"], results_no["Recall@K"], results_no["MRR"]]

x = np.arange(len(metrics))

# توليد ألوان عشوائية
colors = [(random.random(), random.random(), random.random()) for _ in metrics]

plt.figure()
plt.bar(x, values, color=colors)

plt.xticks(x, metrics)
plt.ylabel("Score")
plt.title("Model Performance (Random Colors)")

plt.show()

"""# `SentenceTransformer('all-MiniLM-L6-v2')`"""

df_all.info()

df_job.info()

!pip install rank_bm25

!pip install -q sentence-transformers scikit-learn pandas numpy matplotlib seaborn

# Explicitly uninstall and reinstall transformers and sentence-transformers to resolve potential dependency conflicts
!pip uninstall -y transformers sentence-transformers
!pip install sentence-transformers

"""# ***without improving the ranking and evalution***

***With Job Group Filtering***
"""

import numpy as np
from sentence_transformers import SentenceTransformer, util

# ============================================================
# MODEL + EMBEDDINGS
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_emb = model.encode(df_all['cleanresume'].tolist(), convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp):
    return min(exp / 5, 1)  # normalize between 0 and 1

# ============================================================
# MAIN FUNCTION (IMPROVED BUT SAME IDEA)
# ============================================================
def get_top_cvs_for_job(job_idx, top_k=10):

    job_group = df_job.iloc[job_idx]['job_group']
    results = []

    # 🔥 نحسب threshold ديناميكي لكل job
    job_sims = sim_matrix[:, job_idx]
    dynamic_threshold = np.mean(job_sims) + 0.05  # مرن وذكي

    for i in range(len(df_all)):

        # job group filter (نخليه زي ما هو)
        if df_all.loc[i, 'job_group'] != job_group:
            continue

        sim = sim_matrix[i, job_idx]

        # 🔥 بدل 0.35 الثابت
        if sim < dynamic_threshold:
            continue

        # 🔥 experience
        exp = df_all.loc[i, 'experience_years']
        exp_score = normalize_experience(exp)

        # 🔥 final score (better than raw similarity)
        final_score = (0.8 * sim) + (0.2 * exp_score)

        explanation = []

        if sim > 0.75:
                explanation.append("Very high semantic similarity")
        elif sim > 0.5:
                explanation.append("Moderate semantic similarity")
        else:
                explanation.append("Low semantic similarity")

        if exp >= 3:
                explanation.append("Good experience level")
        else:
                explanation.append("Limited experience")

        # ---------------- result ----------------
        results.append({
                "resume_id": i,
                "cv_text": df_all.loc[i, 'cleanresume'],
                "score": float(final_score),
                "similarity": float(sim),
                "explanation": explanation
            })

    # sort and return outside the loop
    results = sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

    return results

# ============================================================
# TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):

    print(f"\n================ JOB {j} ================")
    print("Job Group:", df_job.iloc[j]['job_group'])


    results = get_top_cvs_for_job(j)

    for rank, r in enumerate(results):

        print("\n----------------------------")

        print("")

        print("Rank:", rank + 1)
        print("CV:\n", df_all.iloc[r["resume_id"]]["cleanresume"][:300])
        print("Score:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))



        print("Explanation:")
        for e in r["explanation"]:
            print(" -", e)

"""# ***Without Job Group fillter***"""

import numpy as np
from sentence_transformers import SentenceTransformer, util

# ============================================================
# MODEL + EMBEDDINGS
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_emb = model.encode(df_all['cleanresume'].tolist(), convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()
# ============================================================
# HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp):
    return min(exp / 5, 1)  # normalize between 0 and 1

# ============================================================
# FUNCTION (NO job_group at all)
# ============================================================

def get_top_cvs_no_group(job_idx, top_k=10):

    results = []

    job_sims = sim_matrix[:, job_idx]
    dynamic_threshold = np.mean(job_sims) + 0.05

    for i in range(len(df_all)):

        sim = sim_matrix[i, job_idx]

        if sim < dynamic_threshold:
            continue

        exp = df_all.loc[i, 'experience_years']
        exp_score = normalize_experience(exp)

        final_score = (0.8 * sim) + (0.2 * exp_score)

        explanation = [
            "No group filtering applied",
            "Semantic matching only"
        ]

        results.append({
            "resume_id": i,
            "cv_text": df_all.loc[i, 'cleanresume'],
            "score": float(final_score),
            "similarity": float(sim),
            "explanation": explanation
        })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):


    print(f"\n================ JOB {j} ================")
    print ("Job Group:", df_job.iloc[j]['job_group'])

    results = get_top_cvs_no_group(j)

    for rank, r in enumerate(results):

        print("\n----------------------------")

        print("")

        print("Rank:", rank + 1)
        print("CV:\n", df_all.iloc[r["resume_id"]]["cleanresume"][:300])
        print("Score:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))



        print("Explanation:")
        for e in r["explanation"]:
            print(" -", e)

"""# ***HYBRID MODEL (SOFT GROUPING)***"""

import numpy as np
from sentence_transformers import SentenceTransformer, util

# ============================================================
# MODEL + EMBEDDINGS
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_emb = model.encode(df_all['cleanresume'].tolist(), convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()
# ============================================================
# HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp):
    return min(exp / 5, 1)  # normalize between 0 and 1

# ============================================================
# FUNCTION (NO job_group at all)
# ============================================================

def get_top_cvs_hybrid(job_idx, top_k=10):

    job_group = df_job.iloc[job_idx]['job_group']
    results = []

    job_sims = sim_matrix[:, job_idx]
    dynamic_threshold = np.mean(job_sims) + 0.05

    for i in range(len(df_all)):

        sim = sim_matrix[i, job_idx]

        if sim < dynamic_threshold:
            continue

        exp = df_all.loc[i, 'experience_years']
        exp_score = normalize_experience(exp)

        # ✔ soft group bonus بدل فلترة
        group_bonus = 0.1 if df_all.loc[i, 'job_group'] == job_group else 0.0

        final_score = (0.8 * sim) + (0.2 * exp_score) + group_bonus

        explanation = [
            "Hybrid scoring applied",
            "Soft group bonus used",
            "Semantic + experience combined"
        ]

        results.append({
            "resume_id": i,
            "cv_text": df_all.loc[i, 'cleanresume'],
            "score": float(final_score),
            "similarity": float(sim),
            "explanation": explanation
        })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):




    results = get_top_cvs_hybrid(j)

    for rank, r in enumerate(results):

        print("\n----------------------------")
        print(f"\n================ JOB {j} ================")
        print ("Job Group:", df_job.iloc[j]['job_group'])

        print("")


        print("Rank:", rank + 1)
        print("CV:\n", df_all.iloc[r["resume_id"]]["cleanresume"][:300])
        print("Score:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))

        print("CV Text:\n", r["cv_text"][:300])  # shorten output

        print("Explanation:")
        for e in r["explanation"]:
            print(" -", e)

"""evaluation"""

threshold = 0.65

ground_truth = {
    j: np.where(sim_matrix[:, j] >= threshold)[0].tolist()
    for j in range(len(df_job))
}
def precision_at_k(pred, true, k):
    pred = pred[:k]
    return len(set(pred) & set(true)) / max(len(pred), 1)

def recall_at_k(pred, true, k):
    return len(set(pred) & set(true)) / max(len(true), 1)

def mrr(pred, true):
    for i, p in enumerate(pred):
        if p in true:
            return 1 / (i + 1)
    return 0
def evaluate_system(pred_fn, K_val=10):

    precisions, recalls, mrrs = [], [], []

    for j in range(len(df_job)):

        results = pred_fn(j)
        pred = [r["resume_id"] for r in results]
        true = ground_truth[j]

        precisions.append(precision_at_k(pred, true, K_val))
        recalls.append(recall_at_k(pred, true, K_val))
        mrrs.append(mrr(pred, true))

    return {
        "Precision@K": np.mean(precisions),
        "Recall@K": np.mean(recalls),
        "MRR":
        np.mean(mrrs)

    }
k=5

results_with = evaluate_system(get_top_cvs_for_job, k)
results_no = evaluate_system(get_top_cvs_no_group, k)
results_hybrid = evaluate_system(get_top_cvs_hybrid, k)
import pandas as pd

df_results = pd.DataFrame([
    ["With Group", results_with["Precision@K"], results_with["Recall@K"], results_with["MRR"]],
    ["No Group", results_no["Precision@K"], results_no["Recall@K"], results_no["MRR"]],
    ["Hybrid", results_hybrid["Precision@K"], results_hybrid["Recall@K"], results_hybrid["MRR"]],
], columns=["Model", "Precision@5", "Recall@5", "MRR"])

df_results

import pandas as pd
import matplotlib.pyplot as plt

df_results = pd.DataFrame([
    ["With Group", 0.630769, 0.182973, 0.761218],
    ["No Group", 0.780769, 0.265736, 0.846154],
    ["Hybrid", 0.688462, 0.206405, 0.823878],
], columns=["Model", "Precision@5", "Recall@5", "MRR"])


plt.figure()

plt.bar(
    df_results["Model"],
    df_results["Precision@5"],
    color=plt.cm.viridis(range(len(df_results)))
)

plt.title("Precision@5 Comparison")
plt.ylabel("Score")
plt.show()

plt.figure()

plt.bar(
    df_results["Model"],
    df_results["Recall@5"],
    color=plt.cm.plasma(range(len(df_results)))
)

plt.title("Recall@5 Comparison")
plt.ylabel("Score")
plt.show()

plt.figure()

plt.bar(
    df_results["Model"],
    df_results["MRR"],
    color=plt.cm.viridis(range(len(df_results)))
)

plt.title("MRR Comparison")
plt.ylabel("Score")
plt.show()

import numpy as np

x = np.arange(len(df_results["Model"]))
width = 0.25

colors1 = plt.cm.viridis(np.linspace(0, 1, len(df_results)))
colors2 = plt.cm.plasma(np.linspace(0, 1, len(df_results)))
colors3 = plt.cm.cividis(np.linspace(0, 1, len(df_results)))

plt.figure()

plt.bar(x - width, df_results["Precision@5"], width, label="Precision@5", color=colors1)
plt.bar(x, df_results["Recall@5"], width, label="Recall@5", color=colors2)
plt.bar(x + width, df_results["MRR"], width, label="MRR", color=colors3)

plt.xticks(x, df_results["Model"])
plt.title("Model Comparison Overview")
plt.legend()
plt.show()

"""# **with improving ranking and evaltion and chunk**

with groub
"""

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util


# ============================================================
# CHUNKING FUNCTION
# ============================================================

def split_text_into_chunks(text, chunk_size=100):
    words = str(text).split()
    chunks = []

    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i + chunk_size])
        if chunk.strip():
            chunks.append(chunk)

    return chunks

# ============================================================
# MODEL + EMBEDDINGS (CHUNK-BASED)
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_chunks = []
resume_map = []  # كل chunk لأي CV

for idx, text in enumerate(df_all['cleanresume']):
    chunks = split_text_into_chunks(text, chunk_size=100)

    for chunk in chunks:
        resume_chunks.append(chunk)
        resume_map.append(idx)

# 🔥 تحسين السرعة: build mapping مرة واحدة
cv_to_chunks = {}

for chunk_idx, cv_idx in enumerate(resume_map):
    if cv_idx not in cv_to_chunks:
        cv_to_chunks[cv_idx] = []
    cv_to_chunks[cv_idx].append(chunk_idx)

# Encode
resume_emb = model.encode(resume_chunks, convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

# Similarity
sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp):
    return min(exp / 5, 1)

# ============================================================
# MAIN FUNCTION (FAST + SAME LOGIC)
# ============================================================

def get_top_cvs_with_group(job_idx, top_k=10):

    job_group = df_job.iloc[job_idx]['job_group']
    results = []

    threshold = np.percentile(sim_matrix[:, job_idx], 60)

    for i in range(len(df_all)):

        # 🔥 استخدام mapping السريع
        chunk_indices = cv_to_chunks.get(i, [])

        if not chunk_indices:
            continue

        sim = max(sim_matrix[k, job_idx] for k in chunk_indices)

        if sim < threshold:
            continue

        exp = normalize_experience(df_all.loc[i, 'experience_years'])

        group_bonus = 0.15 if df_all.loc[i, 'job_group'] == job_group else 0

        final_score = (
            0.65 * sim +
            0.20 * exp +
            group_bonus +
            0.10 * (sim * exp)
        )

        results.append({
            "resume_id": i,
            "score": float(final_score),
            "similarity": float(sim)
        })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# TEST OUTPUT
# ============================================================

for j in range(min(3, len(df_job))):

    print("\n----------------------------")
    print(f"\n================ JOB {j} ================")
    print("Job Group:", df_job.iloc[j]['job_group'])

    results = get_top_cvs_with_group(j)

    for rank, r in enumerate(results):

        print("\n----------------------------")
        print("Rank:", rank + 1)

        print("CV:\n", df_all.iloc[r["resume_id"]]["cleanresume"][:300])

        print("Score:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))

"""without fillter"""

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util
df_all = df_all.drop_duplicates(subset=["cleanresume"]).reset_index(drop=True)

# ============================================================
# 0. CHUNKING FUNCTION
# ============================================================

def split_text_into_chunks(text, chunk_size=100):
    words = str(text).split()
    chunks = []

    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i + chunk_size])
        if chunk.strip():
            chunks.append(chunk)

    return chunks

# ============================================================
# 1. MODEL + EMBEDDINGS (CHUNK-BASED)
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_chunks = []
resume_map = []

for idx, text in enumerate(df_all['cleanresume']):
    chunks = split_text_into_chunks(text, chunk_size=100)

    for chunk in chunks:
        resume_chunks.append(chunk)
        resume_map.append(idx)

# 🔥 FAST MAP
cv_to_chunks = {}
for chunk_idx, cv_idx in enumerate(resume_map):
    if cv_idx not in cv_to_chunks:
        cv_to_chunks[cv_idx] = []
    cv_to_chunks[cv_idx].append(chunk_idx)

# Encode
resume_emb = model.encode(resume_chunks, convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

# Similarity
sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()

# ============================================================
# 2. HELPERS
# ============================================================

def normalize_experience(exp, max_exp=5):
    if pd.isna(exp):
        return 0
    return min(exp / max_exp, 1)

# ============================================================
# 3. NO GROUP MODEL (WITH CHUNKING)
# ============================================================

def get_top_cvs_no_group(job_idx, top_k=10):

    results = []
    seen = set()  #  منع التكرار

    threshold = np.percentile(sim_matrix[:, job_idx], 60)

    for i in cv_to_chunks.keys():  # بدل len(df_all)

        if i in seen:
            continue

        chunk_indices = cv_to_chunks.get(i, [])

        if not chunk_indices:
            continue

        # أفضل chunk فقط
        sim = max(sim_matrix[k, job_idx] for k in chunk_indices)

        if sim < threshold:
            continue

        exp = normalize_experience(df_all.loc[i, 'experience_years'])

        final_score = (
            0.75 * sim +
            0.20 * exp +
            0.05 * (sim * exp)
        )

        results.append({
            "resume_id": i,
            "score": float(final_score),
            "similarity": float(sim)
        })

        seen.add(i)  # 🔥 يمنع التكرار

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# 4. TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):

    print("\n==============================")
    print(f"JOB {j}")
    print("Job Group:", df_job.iloc[j]['job_group'])
    print("==============================\n")

    results = get_top_cvs_no_group(j)

    for rank, r in enumerate(results):

        print("----------------------------")
        print("Rank:", rank + 1)

        print("\nCV (preview):")
        print(df_all.iloc[r["resume_id"]]["cleanresume"][:300])

        print("\nScore:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))

"""hyprid"""

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util
df_all = df_all.drop_duplicates(subset=["cleanresume"]).reset_index(drop=True)

# ============================================================
# 0. CHUNKING FUNCTION
# ============================================================

def split_text_into_chunks(text, chunk_size=100):
    words = str(text).split()
    chunks = []

    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i + chunk_size])
        if chunk.strip():
            chunks.append(chunk)

    return chunks

# ============================================================
# 1. MODEL + EMBEDDINGS (CHUNK-BASED)
# ============================================================

model = SentenceTransformer('all-MiniLM-L6-v2')

resume_chunks = []
resume_map = []

for idx, text in enumerate(df_all['cleanresume']):
    chunks = split_text_into_chunks(text, chunk_size=100)

    for chunk in chunks:
        resume_chunks.append(chunk)
        resume_map.append(idx)

# 🔥 FAST MAP
cv_to_chunks = {}
for chunk_idx, cv_idx in enumerate(resume_map):
    if cv_idx not in cv_to_chunks:
        cv_to_chunks[cv_idx] = []
    cv_to_chunks[cv_idx].append(chunk_idx)

# Encode
resume_emb = model.encode(resume_chunks, convert_to_tensor=True)
job_emb = model.encode(df_job['clean_text'].tolist(), convert_to_tensor=True)

# Similarity
sim_matrix = util.cos_sim(resume_emb, job_emb).cpu().numpy()

# ============================================================
# 2. HELPER FUNCTIONS
# ============================================================

def normalize_experience(exp, max_exp=5):
    if pd.isna(exp):
        return 0
    return min(exp / max_exp, 1)

# ============================================================
# 3. HYBRID MODEL (WITH CHUNKING)
# ============================================================

def get_top_cvs_hybrid(job_idx, top_k=10):

    job_group = df_job.iloc[job_idx]['job_group']
    results = []

    threshold = np.percentile(sim_matrix[:, job_idx], 60)

    for i in range(len(df_all)):

        # 🔥 CHUNK-BASED SIMILARITY
        chunk_indices = cv_to_chunks.get(i, [])

        if not chunk_indices:
            continue

        sim = max(sim_matrix[k, job_idx] for k in chunk_indices)

        if sim < threshold:
            continue

        exp = normalize_experience(df_all.loc[i, 'experience_years'])

        # نفس منطقك (soft group)
        group_bonus = 1 if df_all.loc[i, 'job_group'] == job_group else 0

        interaction = sim * exp

        final_score = (
            0.65 * sim +
            0.20 * exp +
            0.10 * group_bonus +
            0.05 * interaction
        )

        results.append({
            "resume_id": i,
            "score": float(final_score),
            "similarity": float(sim)
        })

    return sorted(results, key=lambda x: x["score"], reverse=True)[:top_k]

# ============================================================
# 4. TEST OUTPUT
# ============================================================

for j in range(min(1, len(df_job))):

    print("\n==============================")
    print(f"JOB {j}")
    print("Job Group:", df_job.iloc[j]['job_group'])
    print("==============================\n")

    results = get_top_cvs_hybrid(j)

    for rank, r in enumerate(results):

        print("----------------------------")
        print("Rank:", rank + 1)

        print("\nCV Preview:")
        print(df_all.iloc[r["resume_id"]]["cleanresume"][:300])

        print("\nScore:", round(r["score"], 4))
        print("Similarity:", round(r["similarity"], 4))

"""improved evaltion with less bieas"""

import numpy as np
import pandas as pd

# ============================================================
# 1. METRICS
# ============================================================

def precision_at_k(pred, true, k):
    pred = pred[:k]
    return len(set(pred) & set(true)) / max(len(pred), 1)

def recall_at_k(pred, true, k):
    return len(set(pred) & set(true)) / max(len(true), 1)

def mrr(pred, true):
    for i, p in enumerate(pred):
        if p in true:
            return 1 / (i + 1)
    return 0


# ============================================================
# 2. WEIGHTING (Inverse Frequency)
# ============================================================

job_group_counts = df_job['job_group'].value_counts().to_dict()

def get_weight(job_group):
    freq = job_group_counts.get(job_group, 1)
    return 1 / freq


# ============================================================
# 3. WEIGHTED EVALUATION FUNCTION
# ============================================================

def evaluate_system_weighted(pred_fn, K=5):

    precisions, recalls, mrrs, weights = [], [], [], []

    for j in range(len(df_job)):

        job_group = df_job.iloc[j]['job_group']
        weight = get_weight(job_group)

        # predictions from system
        results = pred_fn(j)
        pred = [r["resume_id"] for r in results]

        # ====================================================
        # Ground truth (self-similarity top-K)
        # ====================================================
        scores = []

        for i in range(len(df_all)):
            chunk_indices = cv_to_chunks.get(i, [])

            if not chunk_indices:
                continue

            sim = max(sim_matrix[k, j] for k in chunk_indices)
            scores.append((i, sim))

        true = [
            i for i, _ in sorted(scores, key=lambda x: x[1], reverse=True)[:K]
        ]

        # ====================================================
        # Metrics (weighted)
        # ====================================================
        precisions.append(precision_at_k(pred, true, K) * weight)
        recalls.append(recall_at_k(pred, true, K) * weight)
        mrrs.append(mrr(pred, true) * weight)

        weights.append(weight)

    return {
        "Precision@K": sum(precisions) / sum(weights),
        "Recall@K": sum(recalls) / sum(weights),
        "MRR": sum(mrrs) / sum(weights)
    }


# ============================================================
# 4. RUN ALL SYSTEMS
# ============================================================

K = 5

results_with = evaluate_system_weighted(get_top_cvs_with_group, K)
results_no = evaluate_system_weighted(get_top_cvs_no_group, K)
results_hybrid = evaluate_system_weighted(get_top_cvs_hybrid, K)


# ============================================================
# 5. FINAL COMPARISON TABLE
# ============================================================

df_results = pd.DataFrame([
    ["With Group",
     results_with["Precision@K"],
     results_with["Recall@K"],
     results_with["MRR"]],

    ["No Group",
     results_no["Precision@K"],
     results_no["Recall@K"],
     results_no["MRR"]],

    ["Hybrid",
     results_hybrid["Precision@K"],
     results_hybrid["Recall@K"],
     results_hybrid["MRR"]],
],
columns=["Model", "Precision@5 (Weighted)", "Recall@5 (Weighted)", "MRR (Weighted)"])

print("\n=========== WEIGHTED EVALUATION (INVERSE FREQUENCY) ===========\n")
print(df_results)

import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# دالة توليد ألوان عشوائية
# ============================================================

def random_colors(n):
    return np.random.rand(n, 3)  # RGB random colors


# ============================================================
# 1. PRECISION
# ============================================================

plt.figure()
plt.bar(
    df_results["Model"],
    df_results["Precision@5 (Weighted)"],
    color=random_colors(len(df_results))
)
plt.title("Precision@5 Comparison")
plt.ylabel("Score")
plt.show()


# ============================================================
# 2. RECALL
# ============================================================

plt.figure()
plt.bar(
    df_results["Model"],
    df_results["Recall@5 (Weighted)"],
    color=random_colors(len(df_results))
)
plt.title("Recall@5 Comparison")
plt.ylabel("Score")
plt.show()


# ============================================================
# 3. MRR
# ============================================================

plt.figure()
plt.bar(
    df_results["Model"],
    df_results["MRR (Weighted)"],
    color=random_colors(len(df_results))
)
plt.title("MRR Comparison")
plt.ylabel("Score")
plt.show()